### ISSUE TITLE
refactor(test): simplify & fix scripts

### ISSUE THREAD

**Issue by lucasrodes** [owid/covid-19-data#2409]
## The problem
The testing pipeline is currently running very slow, mainly due to two problems:

1. Some sources are not working anymore or don't work properly (slow loading times, large data files, etc.)
2. Some country scripts have very complex code or code that differs from standard library style. This may slow down the execution and difficult maintenance.

All of this makes the process slower and more difficult to debug.

## Goal
The goal of this issue is to provide a list of these scripts so maintainers and contributors can help improve these scripts by either re-writing them or changing the sources in use.

## List of problematic scripts
Find a list of the identified scripts that need refactoring (sorted by priority*):

- Source not working (problem 1):
  - [x] [`kazakhstan.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/batch/kazakhstan.py):  source not working (timeout), script's code is very complex.
  - [x] [`zambia.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/batch/zambia.py): [`make_monotonic()`](https://github.com/owid/covid-19-data/blob/ced7d97a064860d2ac6309ae10bf2b7462a9f5b9/scripts/src/cowidev/testing/utils/utils.py#L4)'s `max_removed_rows` limit exceeded. #2411 
  - [x] [`costa_rica.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/batch/costa_rica.py): 404 error. #2413 
  - [x] [`cambodia.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/incremental/cambodia.py): data extraction is not robust #2414 

- Source very slow (problem 1):
  - [x] [`peru.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/batch/peru.py): source is very slow (large file). #2428
  - [x] [`moldova.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/incremental/moldova.py): very slow script (probably the source). #2427

- Non-standard code (problem 2):
  - [x] [`qatar.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/incremental/qatar.py): non-standard complex code. Historical data is hardcoded into variable [`sample_official_data`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/batch/qatar.py#L37). Alternative could be to move this to the exported file and use [export_datafile](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/utils/base.py#L60) with option `attach=True`. #2432
  - [x] [`sri_lanka.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/incremental/qatar.py): non-standard complex code. Historical data is hardcoded into variable [`sample_official_data`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/batch/sri_lanka.py#L19). Alternative could be to move this to the exported file and use [export_datafile](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/utils/base.py#L60) with option `attach=True`. #2438
  - [x] [`united_arab_emirates.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/incremental/united_arab_emirates.py): non-standard complex code. Historical data is hardcoded into variable [`sample_official_data`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/batch/united_arab_emirates.py#L39). Alternative could be to move this to the exported file and use [export_datafile](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/utils/base.py#L60) with option `attach=True`. #2440 
  - [x] [`senegal.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/incremental/senegal.py): non-standard complex code. Historical data is hardcoded into variable [`sample_official_data`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/batch/senegal.py#L41). Alternative could be to move this to the exported file and use [export_datafile](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/utils/base.py#L60) with option `attach=True`. #2441 
  - [x] [`norway.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/batch/norway.py): non-standard code. #2442 
  - [x] [`saudi_arabia.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/incremental/saudi_arabia.py): non-standard code. #2443 
  - [x] [`rwanda.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/incremental/croatia.py): non-standard code. #2444 
  - [x] [`croatia.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/incremental/croatia.py): non-standard code. #2445 
  - [x] [`taiwan.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/batch/taiwan.py): non-standard code. #2459 
  - [x] [`andorra.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/incremental/andorra.py): non-standard code. #2448 
  - [x] [`north_macedonia.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/incremental/north_macedonia.py): non-standard code. #2455 
  - [x] [`slovenia.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/batch/slovenia.py): non-standard code. #2457
  - [x] [`slovakia.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/batch/slovakia.py): non-standard code. #2458 
  - [x] [`saint_kitts_nevis.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/incremental/saint_kitts_nevis.py): non-standard code. #2456 
  - [x] [`timor.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/incremental/timor.py): non-standard code. #2460 
  - [x] [`tunisia.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/incremental/tunisia.py): non-standard code. #2462 
  - [x] [`nigeria.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/incremental/nigeria.py): non-standard code.
  - [x] [`lebanon.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/incremental/lebanon.py): non-standard code.
  - [x] [`greece.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/incremental/greece.py): non-standard code. #2454 
  - [x] [`equatorial_guinea.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/incremental/equatorial_guinea.py): non-standard code.
  - [x] [`belarus.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/incremental/belarus.py): non-standard code. #2452 
  - [x] [`azerbaijan.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/incremental/azerbaijan.py): non-standard code. #2451 
  - [x] [`antigua_barbuda.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/incremental/antigua_barbuda.py): non-standard code. #2449
  - [x] [`belize.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/incremental/belize.py): non-standard code. #2453 
  
  
## How can you help
- **Requirements**: You need the project library to be installed:

  ```
   cd scripts/
   pip install -e .
   ```
- **Choose a script** from the list above and mention it in a comment, so others don't work on the same script.
- **Which problem** are you addressing?
  - If addressing 1. (complex code), you should refactor the code based on examples such as [`austria.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/batch/austria.py), [`cuba.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/batch/cuba.py), [`laos.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/testing/incremental/laos.py). All of them use [`CountryTestBase`]() class, which eases some common operations. 
  - If addressing 2. (bad source), you need to identify a new source that is more efficient (source data file is smaller, the website is faster to load, etc.).
- Finally, **test** that **the script** is working!
  - We are working [on improving the development environment](https://github.com/owid/covid-19-data/blob/master/scripts/docs/environment.md),  but temporally you need to add the following snippet and run `python country.py`
    ```python
     if __name__ == "__main__":
         Country().export()
     ```
- Once ready, create a PR and ask for a review. If successful, your script will be merged and marked in the list above.

Thank you very much for helping us ❤️ 

## How to use this thread?
This thread is meant for reference and for users to be able to post which scripts they are working on. For questions, suggestions and doubts, please post them in the discussion #2410

---
*We prioritise fixing those scripts that don't execute correctly or that run very slowly over style refactoring. Within each category, we rank prioritisation based on the script's execution times and estimated workload (scripts with higher execution times and estimated workloads are prioritised)

**Comment by Rouein** [comment]
I remember Moldova was one of the faster scripts and that's why I could scrape historical data quickly. Perhaps the server's have slowed down. If that is the case, maybe finding an alternative source, to increase the speed.

**Comment by Rouein** [comment]
I'm working on Moldova and Peru.

**Comment by Rouein** [comment]
-> Qatar

**Comment by lucasrodes** [comment]
Hi @Rouein,
I would:

- Obtain `tests performed` by adding TMA and PCR tests.
- Ideally, batch is preferred. However I can see that the timeseries seem to have some outliers (value drops, even though they measure cumulative values). If it is too complex, Incremental should also be OK!

**Comment by Rouein** [comment]
With Andorra merged, There are no scripts left other than `Lebanon`  and `Kazakhstan` so if anyone can find an alternative source it would be great.

**Comment by lucasrodes** [comment]
@camappel, there are two countries missing `Kazakhstan` and `Lebanon`.

Based on https://github.com/owid/covid-19-data/issues/2409#issuecomment-1036532631, I think it is wise if we switch to manual for both of the countries as the URLs seem not to be maintained anymore.

For Kazakhstan, there is a PCR table at http://www.coronavirus2020.kz/. However, there is a large mismatch with our reports. Perhaps it refers to `people tested`?

For Lebanon, a rapid check led me to https://www.moph.gov.lb/userfiles/images/Prevention/nCoV-%202019/Covid-19-Daily-Summary/16-2-2022-1-eng.png, which reports daily tests (we have been collecting cumulative so far)

**Comment by lucasrodes** [comment]
For now, I have added these countries to `config.yaml` so the scripts are not run.
